name: maestroni
description: An app build for Maestroni

publish_to: "none"

version: 1.0.0+2023060501

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Payment
  tinkoff_acquiring_sdk:
    path: ./tinkoff_acquiring_sdk_flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  stacked: ^3.2.5
  stacked_services: ^1.0.0
  flutter_svg: ^2.0.6
  dart_mappable: ^3.0.1
  chopper: ^6.1.1
  dropdown_button2: ^2.0.0
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.20
  extended_masked_text: ^2.3.1
  dropdown_search: ^5.0.6
  easy_autocomplete: ^1.6.0
  flutter_typeahead: ^4.3.7
  geocoding: ^2.1.0
  path_provider: ^2.0.15
  fast_cached_network_image: ^1.2.0
  iso8601_offset: ^1.1.0
  scrollview_observer: ^1.12.0
  url_launcher: ^6.1.11
  flutter_osm_plugin: ^0.54.2
  equatable: ^2.0.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

  stacked_generator: ^1.3.3
  mockito: ^5.3.2
  flutter_gen_runner: ^5.3.1
  chopper_generator: ^6.0.0
  dart_mappable_builder:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/res/assets/
  style: camel-case
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: false
  ios: true
  image_path_ios: "assets/icons/icon.jpg"
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 16 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#BA2025"
  android_12:
    color: "#BA2025"
    icon_background_color: "#BA2025"
    image: assets/trans.png
